### PR TITLE
Updating deprecated regex syntax by replacing `/r` (ungreedy) with `/U`

### PR DESCRIPTION
**Pull request by mkompanets**
Regex option for ungreedy match `~r/.../r` was deprecated and is replaced with `~r/.../U` in [Elixir 1.3](https://github.com/elixir-lang/elixir/releases/tag/v1.3.0) which generates quite a few warnings.

### CODE REVIEW

**Comment by nurugger07** [comment]
Can you rebase this against master? Sorry, I wanted to get an older PR in first.

**Comment by mkompanets** [comment]
No problem. Will do.

**Comment by nurugger07** [comment]
@mkompanets There appears to be an error. Can you resolve?

**Comment by nurugger07** [comment]
Awesome! Thanks :)

**Pull request merged**
